engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
        python:
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true

ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.py"

exclude_paths:
- test/